apiVersion: v1
kind: Pod
metadata:
  name: REPLACE_POD_NAME  # Will be replaced by deploy_pod_to_node.sh
  namespace: default
spec:
  hostNetwork: true       # Equivalent to --network=host
  restartPolicy: Never
  nodeName: "REPLACE_NODE_NAME"  # Will be replaced by deploy_pod_to_node.sh
  containers:
  - name: networking-debug-container
    image: quay.io/rajjoshi/networking-debug-container:latest
    imagePullPolicy: Always  # Always pull the latest image, even if tag is the same
    # resources:
    #   limits:
    #     nvidia.com/gpu: 8    # Request GPU access (equivalent to --gpus=all)
    securityContext:
      privileged: true    # Provides access to all host devices including /dev/infiniband/*
    
    # Access to InfiniBand devices (privileged mode already provides this, but explicit is better)
    volumeMounts:
    - name: dev-infiniband
      mountPath: /dev/infiniband
    
    command: ["/bin/bash", "-c"]
    args: 
    - |
      echo "=== Networking Debug Container Ready ==="
      echo "Available tools: ib_write_bw, ibv_devinfo, perftest suite, MLNX OFED tools"
      echo "CUDA support: Enabled (use --use_cuda=<id> with perftest)"
      echo ""
      sleep infinity
  
  volumes:
  - name: dev-infiniband
    hostPath:
      path: /dev/infiniband
      type: Directory