apiVersion: v1
kind: Pod
metadata:
  name: networking-debug-pod
  namespace: default
spec:
  hostNetwork: true       # Bypasses CNI to see raw eth0/ib0 interfaces
  restartPolicy: Never
  nodeName: "pokprod-b93r39s1"  # <--- Forces pod to this specific node
  containers:
  - name: networking-debug-container
    # Using a recent NGC PyTorch image (contains CUDA, NCCL, rdma-core)
    image: nvcr.io/nvidia/pytorch:24.03-py3
    securityContext:
      privileged: true    # Required to access /dev/infiniband/*
    command: ["/bin/bash", "-c"]
    # While NGC has rdma-core, 'perftest' (ib_write_bw) isn't always in the path.
    # We install iproute2 (for 'ip') and perftest just to be 100% sure they are available.
    args: 
    - >
      apt-get update && apt-get install -y iproute2 perftest lshw infiniband-diags pciutils ethtool &&
      echo "Ready for debugging. Sleeping..." && 
      sleep infinity