apiVersion: v1
kind: Pod
metadata:
  name: REPLACE_POD_NAME  # Will be replaced by deploy_pod_to_node.sh
  namespace: REPLACE_NAMESPACE  # Will be replaced by deploy_pod_to_node.sh
spec:
  hostNetwork: true       # Equivalent to --network=host
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  nodeName: "REPLACE_NODE_NAME"  # Will be replaced by deploy_pod_to_node.sh
  containers:
  - name: networking-debug-container
    image: quay.io/rajjoshi/networking-debug-container:latest
    imagePullPolicy: Always  # Always pull the latest image, even if tag is the same
    resources:
      limits:
        # GPU resources - will be replaced by deploy_pod_to_node.sh
        # Use --request-nvidia-gpus or --request-amd-gpus to request GPUs
        nvidia.com/gpu: REPLACE_NVIDIA_GPU_COUNT    # NVIDIA GPUs (requires nvidia device plugin)
        amd.com/gpu: REPLACE_AMD_GPU_COUNT          # AMD GPUs (requires AMD device plugin, provides /dev/kfd and /dev/dri)
    securityContext:
      privileged: true    # Provides access to all host devices including /dev/infiniband/*
    
    # Access to InfiniBand devices (privileged mode already provides this, but explicit is better)
    volumeMounts:
    - name: dev-infiniband
      mountPath: /dev/infiniband
    
    command: ["/bin/bash", "-c"]
    args: 
    - |
      echo "=== Networking Debug Container Ready ==="
      echo "Available tools: ib_write_bw, ibv_devinfo, perftest suite, MLNX OFED tools"
      echo "GPU support:"
      echo "  - CUDA/NVIDIA: use --use_cuda=<id> with perftest"
      echo "  - ROCm/AMD: use --use_rocm=<id> with perftest"
      echo ""
      sleep infinity
  
  volumes:
  - name: dev-infiniband
    hostPath:
      path: /dev/infiniband
      type: Directory